[package]
name = "ccp-ironglight-standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
ccp-ironlight = { git= "https://github.com/raftedproc/randomx-rust-wrapper.git", branch = "main"}
generic-array = "=1.1.0"
hex = "0.4.3"
