[package]
name = "ccp-ironglight-standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
ccp-ironlight = { git= "https://github.com/fluencelabs/randomx-rust-wrapper.git", branch = "randomx-plonky3-sp1"}
generic-array = "=1.1.0"
hex = "0.4.3"
